#!/usr/bin/env python3
"""
GA4 Deep Dive - Email Report Sender
Runs reports and sends via AgentMail
"""

import subprocess
import sys
from datetime import datetime
from pathlib import Path

# Add agentmail path
sys.path.insert(0, str(Path.home() / "clawd/skills/agentmail/.venv/lib/python3.14/site-packages"))

try:
    from agentmail import AgentMail
except ImportError:
    print("Installing agentmail...")
    subprocess.run([sys.executable, "-m", "pip", "install", "agentmail"], check=True)
    from agentmail import AgentMail

import json

# Config
SCRIPT_DIR = Path(__file__).parent
VENV_PYTHON = SCRIPT_DIR.parent / ".venv" / "bin" / "python3"
REPORTS_DIR = SCRIPT_DIR.parent / "data" / "reports"
REPORTS_DIR.mkdir(parents=True, exist_ok=True)

# Get API key from OpenClaw config
def get_agentmail_key():
    config_path = Path.home() / ".openclaw" / "openclaw.json"
    with open(config_path) as f:
        config = json.load(f)
    return config.get("skills", {}).get("entries", {}).get("agentmail", {}).get("apiKey")

def run_report(script_name: str, days: int = 14) -> str:
    """Run a deep dive script and capture output."""
    script_path = SCRIPT_DIR / script_name
    
    result = subprocess.run(
        [str(VENV_PYTHON), str(script_path), "solvr", "--days", str(days)],
        capture_output=True,
        text=True,
        timeout=300
    )
    
    return result.stdout + result.stderr

def send_email(to_emails: list, subject: str, body: str):
    """Send email via AgentMail."""
    api_key = get_agentmail_key()
    if not api_key:
        print("❌ No AgentMail API key found")
        return False
    
    client = AgentMail(api_key=api_key)
    
    # Format body as HTML (preserve formatting)
    html_body = f"""
    <html>
    <body style="font-family: monospace; white-space: pre-wrap; background: #1a1a2e; color: #eee; padding: 20px;">
    <pre style="font-size: 12px; line-height: 1.4;">
{body}
    </pre>
    </body>
    </html>
    """
    
    for email in to_emails:
        try:
            client.inboxes.messages.send(
                inbox_id="claudiusthepirateemperor@agentmail.to",
                to=email,
                subject=subject,
                html=html_body
            )
            print(f"✅ Email sent to {email}")
        except Exception as e:
            print(f"❌ Failed to send to {email}: {e}")
    
    return True

def main():
    print("🏴‍☠️ GA4 Deep Dive - Bi-Weekly Report Generator")
    print(f"   Time: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}")
    print()
    
    # Recipients
    recipients = [
        "felipe.cavalcanti.rj@gmail.com",
        "macballona@mac.com"
    ]
    
    # Run reports
    print("📊 Running V3 (Executive Summary)...")
    v3_report = run_report("deep_dive_v3.py", days=14)
    
    print("📊 Running V4 (Full Monty)...")
    v4_report = run_report("deep_dive_v4.py", days=14)
    
    # Combine
    timestamp = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    full_report = f"""
{'═'*80}
   🏴‍☠️  SOLVR BI-WEEKLY ANALYTICS REPORT
   Generated: {timestamp}
   Period: Last 14 days
{'═'*80}

{'='*80}
   PART 1: EXECUTIVE SUMMARY (V3)
{'='*80}

{v3_report}


{'='*80}
   PART 2: THE FULL MONTY (V4)
{'='*80}

{v4_report}


{'═'*80}
   Report generated by Claudius 🏴‍☠️
   Questions? Reply to this email.
{'═'*80}
"""
    
    # Save report
    report_file = REPORTS_DIR / f"solvr_biweekly_{datetime.now().strftime('%Y%m%d_%H%M')}.txt"
    report_file.write_text(full_report)
    print(f"💾 Report saved: {report_file}")
    
    # Send email
    subject = f"🏴‍☠️ Solvr Analytics Report - {datetime.now().strftime('%b %d, %Y')}"
    
    print(f"\n📧 Sending to: {', '.join(recipients)}")
    send_email(recipients, subject, full_report)
    
    print("\n✅ Done!")

if __name__ == "__main__":
    main()
